-- MySQL Script generated by MySQL Workbench
-- Tue Sep  8 14:41:03 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema proyecto_servicios_domicilio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `proyecto_servicios_domicilio` ;

-- -----------------------------------------------------
-- Schema proyecto_servicios_domicilio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto_servicios_domicilio` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `proyecto_servicios_domicilio` ;

-- -----------------------------------------------------
-- Table `proyecto_servicios_domicilio`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_servicios_domicilio`.`categoria` (
  `id_categoria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `uq_categoria_nombre` ON `proyecto_servicios_domicilio`.`categoria` (`nombre` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `proyecto_servicios_domicilio`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_servicios_domicilio`.`usuario` (
  `id_usuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(150) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `rol` ENUM('cliente', 'proveedor') NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `estado_cuenta` ENUM('activo', 'inactivo') NOT NULL DEFAULT 'activo',
  `fecha_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `uq_usuario_email` ON `proyecto_servicios_domicilio`.`usuario` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `proyecto_servicios_domicilio`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_servicios_domicilio`.`cliente` (
  `id_cliente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_cliente`),
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `proyecto_servicios_domicilio`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_cliente_usuario1_idx` ON `proyecto_servicios_domicilio`.`cliente` (`id_cliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `proyecto_servicios_domicilio`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_servicios_domicilio`.`direccion` (
  `id_direccion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_cliente` INT UNSIGNED NOT NULL,
  `es_principal` TINYINT(1) NOT NULL DEFAULT '0',
  `telefono` VARCHAR(255) NOT NULL,
  `ciudad` VARCHAR(100) NOT NULL,
  `barrio_sector` VARCHAR(150) NULL DEFAULT NULL,
  `informacion_complementaria` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `cliente_id_cliente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_direccion`),
  CONSTRAINT `fk_direccion_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `proyecto_servicios_domicilio`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_direccion_cliente1_idx` ON `proyecto_servicios_domicilio`.`direccion` (`cliente_id_cliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `proyecto_servicios_domicilio`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_servicios_domicilio`.`proveedor` (
  `perfil_profesional` TEXT NULL DEFAULT NULL,
  `id_proveedor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_proveedor`),
  CONSTRAINT `fk_proveedor_usuario1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `proyecto_servicios_domicilio`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_proveedor_usuario1_idx` ON `proyecto_servicios_domicilio`.`proveedor` (`id_proveedor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `proyecto_servicios_domicilio`.`disponibilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_servicios_domicilio`.`disponibilidad` (
  `id_disponibilidad` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dia_semana` ENUM('lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo') NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fin` TIME NOT NULL,
  `id_proveedor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_disponibilidad`),
  CONSTRAINT `fk_disponibilidad_proveedor1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `proyecto_servicios_domicilio`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_disponibilidad_proveedor1_idx` ON `proyecto_servicios_domicilio`.`disponibilidad` (`id_proveedor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `proyecto_servicios_domicilio`.`recuperacion_password`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_servicios_domicilio`.`recuperacion_password` (
  `id_recuperacion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario` INT UNSIGNED NOT NULL,
  `codigo_token` VARCHAR(255) NOT NULL,
  `fecha_expiracion` DATETIME NOT NULL,
  `usado` TINYINT(1) NOT NULL DEFAULT '0',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_recuperacion`),
  CONSTRAINT `fk_recuperacion_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `proyecto_servicios_domicilio`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `idx_recuperacion_usuario` ON `proyecto_servicios_domicilio`.`recuperacion_password` (`id_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `proyecto_servicios_domicilio`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_servicios_domicilio`.`servicio` (
  `id_servicio` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_categoria` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `duracion_minutos` SMALLINT UNSIGNED NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `estado` ENUM('activo', 'inactivo') NOT NULL DEFAULT 'activo',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `id_proveedor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_servicio`),
  CONSTRAINT `fk_servicio_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `proyecto_servicios_domicilio`.`categoria` (`id_categoria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_servicio_proveedor1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `proyecto_servicios_domicilio`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `idx_servicio_categoria` ON `proyecto_servicios_domicilio`.`servicio` (`id_categoria` ASC) VISIBLE;

CREATE INDEX `fk_servicio_proveedor1_idx` ON `proyecto_servicios_domicilio`.`servicio` (`id_proveedor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `proyecto_servicios_domicilio`.`servicio_insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_servicios_domicilio`.`servicio_insumo` (
  `id_insumo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_servicio` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `tipo` ENUM('insumo', 'equipo') NOT NULL DEFAULT 'insumo',
  PRIMARY KEY (`id_insumo`),
  CONSTRAINT `fk_insumo_servicio`
    FOREIGN KEY (`id_servicio`)
    REFERENCES `proyecto_servicios_domicilio`.`servicio` (`id_servicio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `idx_insumo_servicio` ON `proyecto_servicios_domicilio`.`servicio_insumo` (`id_servicio` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `proyecto_servicios_domicilio`.`servicio_multimedia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_servicios_domicilio`.`servicio_multimedia` (
  `id_multimedia` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_servicio` INT UNSIGNED NOT NULL,
  `tipo_archivo` ENUM('foto', 'video') NOT NULL,
  `url_archivo` VARCHAR(500) NOT NULL,
  `orden` SMALLINT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_multimedia`),
  CONSTRAINT `fk_multimedia_servicio`
    FOREIGN KEY (`id_servicio`)
    REFERENCES `proyecto_servicios_domicilio`.`servicio` (`id_servicio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `idx_multimedia_servicio` ON `proyecto_servicios_domicilio`.`servicio_multimedia` (`id_servicio` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `proyecto_servicios_domicilio`.`solicitud_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_servicios_domicilio`.`solicitud_reserva` (
  `id_solicitud` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_servicio` INT UNSIGNED NOT NULL,
  `nombre_servicio_snapshot` VARCHAR(150) NOT NULL,
  `precio_snapshot` DECIMAL(10,2) NOT NULL,
  `duracion_snapshot_minutos` SMALLINT UNSIGNED NOT NULL,
  `fecha_hora_solicitada` DATETIME NOT NULL,
  `fecha_hora_propuesta` DATETIME NULL DEFAULT NULL,
  `direccion_texto` VARCHAR(255) NOT NULL,
  `barrio_sector` VARCHAR(150) NULL DEFAULT NULL,
  `informacion_complementaria` VARCHAR(255) NULL DEFAULT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  `estado` ENUM('pendiente', 'sugerida', 'aceptada', 'completada', 'cancelada', 'rechazada') NOT NULL DEFAULT 'pendiente',
  `motivo_rechazo_cancelacion` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `id_cliente` INT UNSIGNED NOT NULL,
  `id_proveedor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_solicitud`),
  CONSTRAINT `fk_solicitud_servicio`
    FOREIGN KEY (`id_servicio`)
    REFERENCES `proyecto_servicios_domicilio`.`servicio` (`id_servicio`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_solicitud_reserva_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `proyecto_servicios_domicilio`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_reserva_proveedor1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `proyecto_servicios_domicilio`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `idx_solicitud_servicio` ON `proyecto_servicios_domicilio`.`solicitud_reserva` (`id_servicio` ASC) VISIBLE;

CREATE INDEX `fk_solicitud_reserva_cliente1_idx` ON `proyecto_servicios_domicilio`.`solicitud_reserva` (`id_cliente` ASC) VISIBLE;

CREATE INDEX `fk_solicitud_reserva_proveedor1_idx` ON `proyecto_servicios_domicilio`.`solicitud_reserva` (`id_proveedor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `proyecto_servicios_domicilio`.`zona_cobertura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_servicios_domicilio`.`zona_cobertura` (
  `id_zona` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ciudad` VARCHAR(100) NOT NULL,
  `barrio_sector` VARCHAR(150) NULL DEFAULT NULL,
  `id_proveedor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_zona`),
  CONSTRAINT `fk_zona_cobertura_proveedor1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `proyecto_servicios_domicilio`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_zona_cobertura_proveedor1_idx` ON `proyecto_servicios_domicilio`.`zona_cobertura` (`id_proveedor` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE TABLE IF NOT EXISTS token_invalido (
    id_token INT UNSIGNED NOT NULL AUTO_INCREMENT,
    token VARCHAR(500) NOT NULL,
    fecha_invalidacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_token)
) ENGINE = InnoDB;

ALTER TABLE direccion DROP COLUMN id_cliente;